/* Generated by training/train_model.py. Do not edit by hand.
 * Scores are attack probabilities in [0, 1]. Training/evaluation data and
 * validation status are recorded in models/model.json.
 */
#ifndef ADOS_MODEL_H
#define ADOS_MODEL_H

#define ADOS_FEATURE_COUNT 4
#define ADOS_MODEL_ENFORCE_ALLOWED 0
#define ADOS_MODEL_SOURCE_KIND "local-capture-unvalidated"
#define ADOS_MODEL_METADATA "model.json"

static inline float ados_model_score(const float features[ADOS_FEATURE_COUNT]) {
    if (features == 0) return 0.0f;
    if ((double)features[0] <= 2.5) {
        if ((double)features[3] <= 0.5) {
            if ((double)features[1] <= 56) {
                return 0.0585192216f;
            } else {
                return 0.0f;
            }
        } else {
            return 0.0f;
        }
    } else {
        return 1.0f;
    }
}

#endif
